logo: "/assets/PaperworkTransparent.svg"
title: Paperwork
description: The documentation for Paperwork library and the core, open source, Scryber PDF creation library for dotnet.
theme: just-the-docs
color_scheme: dark

url: https://www.paperworkday.info

aux_links:
  .git: https://github.com/richard-scryber/scryber.core
  .com: https://www.paperworkday.com
  .studio: https://paperworkday.studio
  aux_links_new_tab: true

heading_anchors: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

ga_tracking: G-C7R7SHJGSR
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

    

