logo: "/assets/PaperworkLogoAndName.png"
title: Scryber.Core
description: The documentation for the Scryber.Code open source PDF creation library for dotnet.
theme: just-the-docs
color_scheme: light

url: https://www.paperworkday.net

aux_links:
  .git: https://github.com/just-the-docs/just-the-docs-template
  .com: https://www.paperworkday.com
  .studio: https://paperworkday.studio
